workflows:
  rust-build:
    name: Rust Build
    instance_type: mac_mini_m1 # or another suitable instance type
    scripts:
      - name: Install Rust
        script: |
          cd frontend && yarn install && yarn build:http
          cd ..
          curl -OL https://golang.org/dl/go1.22.0.darwin-arm64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.0.darwin-arm64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          ~/go/bin/wails build -tags "wails"
    artifacts:
      - build/*

